[tool.poetry]
name = "CRISP-DM template"
version = "0.1.0"
description = ""
authors = ["Michael Verdegaal <michaelverdegaal@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^3.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
